// <auto-generated />
using System;
using AutoParkas.Core.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Pavyzdys2.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    partial class AppDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoParkas.Core.Models.Automobilis", b =>
                {
                    b.Property<int>("AutomobilioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutomobilioId"));

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ParosKaina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PirmosRegData")
                        .HasColumnType("date");

                    b.HasKey("AutomobilioId");

                    b.ToTable("Automobiliai");
                });

            modelBuilder.Entity("AutoParkas.Core.Models.Klientas", b =>
                {
                    b.Property<int>("KlientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlientoId"));

                    b.Property<long>("AsmensKodas")
                        .HasColumnType("bigint");

                    b.Property<int?>("NuomuojamasAutoAutomobilioId")
                        .HasColumnType("int");

                    b.Property<string>("VardasPavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlientoId");

                    b.HasIndex("NuomuojamasAutoAutomobilioId");

                    b.ToTable("Klientai");
                });

            modelBuilder.Entity("AutoParkas.Core.Models.Klientas", b =>
                {
                    b.HasOne("AutoParkas.Core.Models.Automobilis", "NuomuojamasAuto")
                        .WithMany()
                        .HasForeignKey("NuomuojamasAutoAutomobilioId");

                    b.Navigation("NuomuojamasAuto");
                });
#pragma warning restore 612, 618
        }
    }
}
